// SPDX-License-Identifier: 0BSD
#pragma once
#include <stdint.h>

namespace SndData {
  extern const uint16_t sampleCountPerFrame[32];
  extern const uint16_t frequencyPerPitch[1728];
  extern const uint16_t waveTables[27520];

  static inline int waveKind(int channelKind, int duty) {
    // channel kind 0 => sine     => 0
    // channel kind 1 => triangle => 1
    // channel kind 2 => saw      => 2
    // channel kind 3 => square   => 3 + duty
    return channelKind < 3 ? channelKind : 3 + duty;
  }

  static inline int waveBand(int pitch) {
    /*
    const A4 = 57;
    const div = 16;
    const nyquist = 32768 / 2;
    for (let lp = 1; lp <= 8; lp++) {
      const h = (1024 >> lp) - 1; // highest harmonic
      const p = div * (A4 + 12 * Math.log2(nyquist / (440 * h)));
      console.log(lp, Math.floor(p) + 1);
    }
    */
    if (pitch < 187) return 0;
    if (pitch < 380) return 1;
    if (pitch < 573) return 2;
    if (pitch < 767) return 3;
    if (pitch < 963) return 4;
    if (pitch < 1164) return 5;
    if (pitch < 1375) return 6;
    if (pitch < 1610) return 7;
    return 8;
  }

  static inline const int16_t *waveTable(int wkind, int band, int *size) {
    // generated by hand based on SndDataWaveTables.inc
    static constexpr struct { int16_t offset; int16_t size; } offsetSize[] = {
      // sine
      {     0, 1024 }, {  1024, 512 }, {  1536, 256 },
      {  1792,  128 }, {  1792, 128 }, {  1792, 128 },
      {  1792,  128 }, {  1792, 128 }, {  1792, 128 },
      // triangle
      {  1920, 1024 }, {  2944, 512 }, {  3456, 256 },
      {  3712,  128 }, {  3840, 128 }, {  3968, 128 },
      {  4096,  128 }, {  4224, 128 }, {  4352, 128 },
      // saw
      {  4480, 1024 }, {  5504, 512 }, {  6016, 256 },
      {  6272,  128 }, {  6400, 128 }, {  6528, 128 },
      {  6656,  128 }, {  6784, 128 }, {  6912, 128 },
      // square1
      {  7040, 1024 }, {  8064, 512 }, {  8576, 256 },
      {  8832,  128 }, {  8960, 128 }, {  9088, 128 },
      {  9216,  128 }, {  9344, 128 }, {  9472, 128 },
      // square2
      {  9600, 1024 }, { 10624, 512 }, { 11136, 256 },
      { 11392,  128 }, { 11520, 128 }, { 11648, 128 },
      { 11776,  128 }, { 11904, 128 }, { 12032, 128 },
      // square3
      { 12160, 1024 }, { 13184, 512 }, { 13696, 256 },
      { 13952,  128 }, { 14080, 128 }, { 14208, 128 },
      { 14336,  128 }, { 14464, 128 }, { 14592, 128 },
      // square4
      { 14720, 1024 }, { 15744, 512 }, { 16256, 256 },
      { 16512,  128 }, { 16640, 128 }, { 16768, 128 },
      { 16896,  128 }, { 17024, 128 }, { 17152, 128 },
      // square5
      { 17280, 1024 }, { 18304, 512 }, { 18816, 256 },
      { 19072,  128 }, { 19200, 128 }, { 19328, 128 },
      { 19456,  128 }, { 19584, 128 }, { 19712, 128 },
      // square6
      { 19840, 1024 }, { 20864, 512 }, { 21376, 256 },
      { 21632,  128 }, { 21760, 128 }, { 21888, 128 },
      { 22016,  128 }, { 22144, 128 }, { 22272, 128 },
      // square7
      { 22400, 1024 }, { 23424, 512 }, { 23936, 256 },
      { 24192,  128 }, { 24320, 128 }, { 24448, 128 },
      { 24576,  128 }, { 24704, 128 }, { 24832, 128 },
      // square8
      { 24960, 1024 }, { 25984, 512 }, { 26496, 256 },
      { 26752,  128 }, { 26880, 128 }, { 27008, 128 },
      { 27136,  128 }, { 27264, 128 }, { 27392, 128 },
    };
    const auto &os = offsetSize[wkind * 9 + band];
    *size = os.size;
    return (const int16_t *)(waveTables + os.offset);
  }
};
